enum FilterType{
  MONTHLY, ANUALY
}

const SHARED_PREFERENCES_LAST_LOGIN_USED = "SHARED_PREFERENCES_LAST_LOGIN_USED";
const SHARED_PREFERENCES_USE_BIOMETRIC_LOGIN = "SHARED_PREFERENCES_USE_BIOMETRIC_LOGIN";