enum FilterType{
  MONTHLY, ANUALY
}

const SHARED_PREFERENCES_STOREOWNER_NAME = "SHARED_PREFERENCES_STOREOWNER_NAME";
const SHARED_PREFERENCES_STOREOWNER_DATABASE = "SHARED_PREFERENCES_STOREOWNER_DATABASE";
const SHARED_PREFERENCES_STOREOWNER_STORE_LIST = "SHARED_PREFERENCES_STOREOWNER_STORE_LIST";
const SHARED_PREFERENCES_LAST_LOGIN_USED = "SHARED_PREFERENCES_LAST_LOGIN_USED";